stages:
  - backup
  - build

variables:
  DB_USER: "appuser"
  DB_PASS: "appuserpwd"
  DB_DSN: "oracle:1521/XEPDB1"

backup:
  stage: backup
  image: container-registry.oracle.com/database/sqlcl:latest
  script:
    - mkdir -p backups
    - timestamp=$(date +%Y%m%d_%H%M%S)
    - echo "Generando backup lógico..."
    - sql /nolog <<EOF
      connect $DB_USER/$DB_PASS@$DB_DSN
      @scripts/generar_backup.sql $timestamp
      EOF
  artifacts:
    paths:
      - backups/
    expire_in: 1 week

build_deploy_sql:
  stage: build
  image: python:3.11
  script:
    - python deploy.py
  artifacts:
    paths:
      - deploy_*.sql
    expire_in: 1 week
